# Generated by Django 4.2.7 on 2023-11-20 15:11

import catalog.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import orders.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_alter_category_options_alter_fridgedetails_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ship_to', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buying_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('buying_discount_percent', models.DecimalField(decimal_places=2, max_digits=5, validators=[catalog.validators.validate_percent])),
                ('amount', models.PositiveIntegerField(validators=[orders.validators.non_zero_validator])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='orders.OrderProducts', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='orderproducts',
            constraint=models.UniqueConstraint(fields=('order', 'product'), name='unique_product_in_order'),
        ),
    ]
