# Generated by Django 4.2.7 on 2023-11-29 13:07

import catalog.validators
from django.db import migrations, models
import orders.validators
import product_details.models


class Migration(migrations.Migration):

    dependencies = [
        ('product_details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='decorationdetails',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[orders.validators.non_zero_validator]),
        ),
        migrations.AlterField(
            model_name='decorationdetails',
            name='height_cm',
            field=product_details.models.DimensionField(decimal_places=2, max_digits=5, validators=[catalog.validators.positive_decimal_validator, catalog.validators.positive_decimal_validator]),
        ),
        migrations.AlterField(
            model_name='decorationdetails',
            name='length_cm',
            field=product_details.models.DimensionField(decimal_places=2, max_digits=5, validators=[catalog.validators.positive_decimal_validator, catalog.validators.positive_decimal_validator]),
        ),
        migrations.AlterField(
            model_name='decorationdetails',
            name='width_cm',
            field=product_details.models.DimensionField(decimal_places=2, max_digits=5, validators=[catalog.validators.positive_decimal_validator, catalog.validators.positive_decimal_validator]),
        ),
        migrations.AlterField(
            model_name='garlanddetails',
            name='length_meters',
            field=product_details.models.DimensionField(decimal_places=2, max_digits=5, validators=[catalog.validators.positive_decimal_validator, catalog.validators.positive_decimal_validator]),
        ),
        migrations.AlterField(
            model_name='giftwrapdetails',
            name='length_cm',
            field=product_details.models.DimensionField(decimal_places=2, max_digits=5, validators=[catalog.validators.positive_decimal_validator, catalog.validators.positive_decimal_validator]),
        ),
        migrations.AlterField(
            model_name='giftwrapdetails',
            name='width_cm',
            field=product_details.models.DimensionField(decimal_places=2, max_digits=5, validators=[catalog.validators.positive_decimal_validator, catalog.validators.positive_decimal_validator]),
        ),
        migrations.AlterField(
            model_name='illuminationdetails',
            name='height_cm',
            field=product_details.models.DimensionField(decimal_places=2, max_digits=5, validators=[catalog.validators.positive_decimal_validator, catalog.validators.positive_decimal_validator]),
        ),
        migrations.AlterField(
            model_name='illuminationdetails',
            name='length_cm',
            field=product_details.models.DimensionField(decimal_places=2, max_digits=5, validators=[catalog.validators.positive_decimal_validator, catalog.validators.positive_decimal_validator]),
        ),
        migrations.AlterField(
            model_name='illuminationdetails',
            name='width_cm',
            field=product_details.models.DimensionField(decimal_places=2, max_digits=5, validators=[catalog.validators.positive_decimal_validator, catalog.validators.positive_decimal_validator]),
        ),
        migrations.AlterField(
            model_name='wreathdetails',
            name='length_cm',
            field=product_details.models.DimensionField(decimal_places=2, max_digits=5, validators=[catalog.validators.positive_decimal_validator, catalog.validators.positive_decimal_validator]),
        ),
        migrations.AlterField(
            model_name='wreathdetails',
            name='width_cm',
            field=product_details.models.DimensionField(decimal_places=2, max_digits=5, validators=[catalog.validators.positive_decimal_validator, catalog.validators.positive_decimal_validator]),
        ),
    ]
