# Generated by Django 4.2.7 on 2023-11-09 14:38

import catalog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5, validators=[catalog.models.validate_percent])),
                ('picture', models.ImageField(upload_to='products')),
                ('units_available', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('details_id', models.PositiveIntegerField()),
                ('details_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'indexes': [models.Index(fields=['details_content_type', 'details_id'], name='catalog_pro_details_de1d5a_idx')],
            },
        ),
    ]
