# Generated by Django 4.2.7 on 2023-11-29 13:07

import catalog.validators
from decimal import Decimal
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_category_options_alter_fridgedetails_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[catalog.validators.validate_percent]),
        ),
        migrations.AlterField(
            model_name='product',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
