# Generated by Django 4.2.7 on 2023-12-01 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_product_discount_percent_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FridgeDetails',
        ),
        migrations.DeleteModel(
            name='PhoneDetails',
        ),
    ]
